### ISSUE TITLE
Unknown element type TRIANGLE

### ISSUE THREAD

**Issue by ilyasst** [IaPCS/gmsh-exodus-converter#1]
I converted the file 2D fie [plate_test_element2.msh](https://github.com/diehlpk/gmsh-exodus-converter/blob/master/test_files/plate_test_element2.msh) as a .g file using the script.
Then, I tried using Peridigm to load this file with a dummy.peridigm input deck.
I get the following error:

```
adminu@a4217-03:/mnt/hgfs/Peridigm_shared/Gmsh_to_Exodus2$ Peridigm specimen.peridigm

-- Peridigm
-- version 1.4.1

/root/install/Peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:409:

Throw number = 1

Throw test that evaluated to true: true


**** Error in loadData(), unknown element type TRIANGLE.

Wallclock Time (seconds):
  Total            0.021
```

@diehlpk , any ideas ?

**Comment by ilyasst** [comment]
Similarly for elements type 3:

```
adminu@a4217-03:/mnt/hgfs/Peridigm_shared/Gmsh_to_Exodus2$ Peridigm specimen.peridigm

-- Peridigm
-- version 1.4.1

/root/install/Peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:409:

Throw number = 1

Throw test that evaluated to true: true


**** Error in loadData(), unknown element type QUAD.

Wallclock Time (seconds):
  Total             0.05

```

**Comment by diehlpk** [comment]
Looking at the Source Code of Peridigm shows that only 3 types of elements are allowed to use.

00378     if(numElemThisBlock > 0){
00379       string elemTypeString(elemType);
00380       boost::to_upper(elemTypeString);
00381       if(elemTypeString == string("SPHERE"))
00382         exodusElementType = SPHERE_ELEMENT;
00383       else if(elemTypeString == string("TET") || elemTypeString == string("TETRA") || elemTypeString == string("TET4") || elemTypeString == string("TET10"))
00384         exodusElementType = TET_ELEMENT;
00385       else if(elemTypeString == string("HEX") || elemTypeString == string("HEX8") || elemTypeString == string("HEX20"))
00386         exodusElementType = HEX_ELEMENT;
00387       else{
00388         string msg = "\n***\* Error in loadData(), unknown element type " + elemTypeString + ".\n";
00389         TEUCHOS_TEST_FOR_EXCEPT_MSG(true, msg);
00390       }

**Comment by diehlpk** [comment]
Using 4-node tetrahedron as a grid type works for loading grids to Peridigm. I
