### ISSUE TITLE
The internal point is lost after conversion

### ISSUE THREAD

**Issue by YudanJIN** [IaPCS/gmsh-exodus-converter#5]
Hello. Me again.
I found that after I run the command of `convert.py`, it worked, but it lost the points internal.
> before
![screenshot from 2017-03-23 18-10-37](https://cloud.githubusercontent.com/assets/26431272/24261775/5aa3a188-0ff8-11e7-9a45-83b23446fbdb.png)
> after
![screenshot from 2017-03-23 18-37-06](https://cloud.githubusercontent.com/assets/26431272/24261780/5f2f3b9a-0ff8-11e7-849e-e4d07cc89983.png)

**Comment by diehlpk** [comment]
Can you please provide us your mesh file for testing?

**Comment by diehlpk** [comment]
And be aware that all elements have to be from the same type. For 3D at elements have to be 4-node tetrahedrons. Have you check this?

**Comment by YudanJIN** [comment]
this is my document of mesh in format `.txt`. I have chosen the option `Recombine all triangular meshes`
[mesh.txt](https://github.com/IaPCS/gmsh-exodus-converter/files/867380/mesh.txt)

**Comment by diehlpk** [comment]
Ok, I look at it and changed the code to have the inner points too. Now, it looks like this 

![new](https://cloud.githubusercontent.com/assets/3922435/24295852/01e7fc3a-1073-11e7-8d8e-3f6ce474b111.png)

Now you just can execute

`python convert.py -i mesh.txt -o test.e`

and get this result above.

**Comment by YudanJIN** [comment]
thank you very much
