### ISSUE TITLE
meshio

### ISSUE THREAD

**Issue by nschloe** [IaPCS/gmsh-exodus-converter#6]
The code in this repo is probably obsoleted by [meshio](https://github.com/nschloe/meshio):
```python
meshio-convert input.msh output.e
```
(Btw, I'd used `vtk` in meshio once, but found it too large (and unreliable) as a dependency. meshio handles VTK files (and Exodus) manually now.)

**Comment by diehlpk** [comment]
Thanks, for mention this. We will add a note to our readme.
